### ISSUE TITLE
Naming rules for namespaces are violated

### ISSUE THREAD

**Issue by mudrd8mz** [andreasschenkel/moodle-local_feedbackchoicegenerator#12]
Current namespaces like `local_feedbackchoicegenerator\View` or `local_feedbackchoicegenerator\Security` violate the naming rules specified at https://docs.moodle.org/dev/Coding_style#Rules_for_level2

If such a granularity is needed (which I personally doubt), then the right namespace would be e.g. `local_feedbackchoicegenerator\local\View`

**Comment by andreasschenkel** [comment]
Solved with Release v2.0.4
