### ISSUE TITLE
Hard coded English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [andreasschenkel/moodle-local_feedbackchoicegenerator#13]
Hi,
I was testing your plugin with the Mexican Spanish language pack and I noticed that the strings for 'Option 1', 'Option 2', 'Option 3' , etc are hard-coded and not available for translation in AMOS.

Please replace that string constant 'Option' with a string variable that can be translated in AMOS.

Thanks in advance.

![Hard coded English string](https://user-images.githubusercontent.com/2671923/151712067-5b68863e-53b5-4078-bef1-1643857b4204.png)

**Comment by andreasschenkel** [comment]
Solved with Release v2.0.4

**Comment by germanvaleroelizondo** [comment]
Thanks a lot.

**Comment by germanvaleroelizondo** [comment]
When will that version 2.0.4  be available for download at https://moodle.org/plugins/local_feedbackchoicegenerator/versions ?
